package com.ulearning.ulms.content.schoolbook.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 * <p/>
 * This is an object that contains data related to the M_TEACHSORT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class table="M_TEACHSORT"
 */
public abstract class BaseMTeachsort implements Serializable
{
        public static String PROP_BSIFBOOKNAME = "bsifbookname";
        public static String PROP_TCSTQUANTITY = "tcstquantity";
        public static String PROP_REMARK2 = "remark2";
        public static String PROP_BSIFID = "bsifid";
        public static String PROP_TCSTTOTAL = "tcsttotal";
        public static String PROP_TCSTPRICE = "tcstprice";
        public static String PROP_REMARK3 = "remark3";
        public static String PROP_REMARK1 = "remark1";
        public static String PROP_ID = "id";
        private int hashCode = Integer.MIN_VALUE;

        // primary key
        private long _id;

        // fields
        private java.lang.Integer _bsifid;
        private java.lang.String _bsifbookname;
        private Float _tcstprice;
        private Integer _tcstquantity;
        private Float _tcsttotal;
        private java.lang.String _remark1;
        private java.lang.String _remark2;
        private java.lang.String _remark3;

        // constructors
        public BaseMTeachsort()
        {
                initialize();
        }

        /**
         * Constructor for primary key
         */
        public BaseMTeachsort(long _id)
        {
                this.setId(_id);
                initialize();
        }

        protected void initialize()
        {
        }

        /**
         * Return the unique identifier of this class
         *
         * @hibernate.id generator-class="sequence"
         * column="TCSTID"
         */
        public long getId()
        {
                return _id;
        }

        /**
         * Set the unique identifier of this class
         *
         * @param _id the new ID
         */
        public void setId(long _id)
        {
                this._id = _id;
                this.hashCode = Integer.MIN_VALUE;
        }

        /**
         * Return the value associated with the column: BSIFID
         */
        public java.lang.Integer getBsifid()
        {
                return _bsifid;
        }

        /**
         * Set the value related to the column: BSIFID
         *
         * @param _bsifid the BSIFID value
         */
        public void setBsifid(java.lang.Integer _bsifid)
        {
                this._bsifid = _bsifid;
        }

        /**
         * Return the value associated with the column: BSIFBOOKNAME
         */
        public java.lang.String getBsifbookname()
        {
                return _bsifbookname;
        }

        /**
         * Set the value related to the column: BSIFBOOKNAME
         *
         * @param _bsifbookname the BSIFBOOKNAME value
         */
        public void setBsifbookname(java.lang.String _bsifbookname)
        {
                this._bsifbookname = _bsifbookname;
        }

        /**
         * Return the value associated with the column: TCSTPRICE
         */
        public Float getTcstprice()
        {
                return _tcstprice;
        }

        /**
         * Set the value related to the column: TCSTPRICE
         *
         * @param _tcstprice the TCSTPRICE value
         */
        public void setTcstprice(Float _tcstprice)
        {
                this._tcstprice = _tcstprice;
        }

        /**
         * Return the value associated with the column: TCSTQUANTITY
         */
        public Integer getTcstquantity()
        {
                return _tcstquantity;
        }

        /**
         * Set the value related to the column: TCSTQUANTITY
         *
         * @param _tcstquantity the TCSTQUANTITY value
         */
        public void setTcstquantity(Integer _tcstquantity)
        {
                this._tcstquantity = _tcstquantity;
        }

        /**
         * Return the value associated with the column: TCSTTOTAL
         */
        public Float getTcsttotal()
        {
                return _tcsttotal;
        }

        /**
         * Set the value related to the column: TCSTTOTAL
         *
         * @param _tcsttotal the TCSTTOTAL value
         */
        public void setTcsttotal(Float _tcsttotal)
        {
                this._tcsttotal = _tcsttotal;
        }

        /**
         * Return the value associated with the column: REMARK1
         */
        public java.lang.String getRemark1()
        {
                return _remark1;
        }

        /**
         * Set the value related to the column: REMARK1
         *
         * @param _remark1 the REMARK1 value
         */
        public void setRemark1(java.lang.String _remark1)
        {
                this._remark1 = _remark1;
        }

        /**
         * Return the value associated with the column: REMARK2
         */
        public java.lang.String getRemark2()
        {
                return _remark2;
        }

        /**
         * Set the value related to the column: REMARK2
         *
         * @param _remark2 the REMARK2 value
         */
        public void setRemark2(java.lang.String _remark2)
        {
                this._remark2 = _remark2;
        }

        /**
         * Return the value associated with the column: REMARK3
         */
        public java.lang.String getRemark3()
        {
                return _remark3;
        }

        /**
         * Set the value related to the column: REMARK3
         *
         * @param _remark3 the REMARK3 value
         */
        public void setRemark3(java.lang.String _remark3)
        {
                this._remark3 = _remark3;
        }

        public boolean equals(Object obj)
        {
                if (null == obj)
                {
                        return false;
                }

                if (!(obj instanceof com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachsort))
                {
                        return false;
                }
                else
                {
                        com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachsort mObj =
                                (com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachsort) obj;

                        return (this.getId() == mObj.getId());
                }
        }

        public int hashCode()
        {
                if (Integer.MIN_VALUE == this.hashCode)
                {
                        return (int) this.getId();
                }

                return this.hashCode;
        }

        public String toString()
        {
                return super.toString();
        }
}
