package com.ulearning.ulms.content.schoolbook.model.dao;

import com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachmailbillTabDAO;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 * <p/>
 * This is the object class that relates to the M_TEACHMAILBILL_TAB table.
 * Any customizations belong here.
 */
public class MTeachmailbillTabDAO extends BaseMTeachmailbillTabDAO
{
}
