package com.ulearning.ulms.content.schoolbook.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 * <p/>
 * This is an object that contains data related to the M_TEACHBESEINFO_TAB table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class table="M_TEACHBESEINFO_TAB"
 */
public abstract class BaseMTeachbeseinfoTab implements Serializable
{
        public static String PROP_BSIFPUBLISHNAME = "bsifpublishname";
        public static String PROP_BSIFPRICE = "bsifprice";
        public static String PROP_ISBN = "isbn";
        public static String PROP_BSIFWORD = "bsifword";
        public static String PROP_BSIFINTR = "bsifintr";
        public static String PROP_REMARK1 = "remark1";
        public static String PROP_BSIFAPPENDDATE = "bsifappenddate";
        public static String PROP_REMARK2 = "remark2";
        public static String PROP_BSIFPUBLISHID = "bsifpublishid";
        public static String PROP_BDIFSORTNAME = "bdifsortname";
        public static String PROP_BSIFMEMO = "bsifmemo";
        public static String PROP_BSIFEDITOR = "bsifeditor";
        public static String PROP_BSIFPUBLISHDATE = "bsifpublishdate";
        public static String PROP_BSIFAUTHOR = "bsifauthor";
        public static String PROP_BSIFAPPENDDEPT = "bsifappenddept";
        public static String PROP_REMARK3 = "remark3";
        public static String PROP_BSIFBOOKNAME = "bsifbookname";
        public static String PROP_BSIFMAILPRICE = "bsifmailprice";
        public static String PROP_BSIFCOVER = "bsifcover";
        public static String PROP_REMARK4 = "remark4";
        public static String PROP_BSIFCATALONG = "bsifcatalong";
        public static String PROP_BSIFSORTID = "bsifsortid";
        public static String PROP_BSIFIMPRESSION = "bsifimpression";
        public static String PROP_BSIFHOLDTRUE = "bsifholdtrue";
        public static String PROP_REMARK5 = "remark5";
        public static String PROP_ID = "id";
        private int hashCode = Integer.MIN_VALUE;

        // primary key
        private long _id;

        // fields
        private java.lang.String _isbn;
        private java.lang.String _bsifbookname;
        private java.lang.Integer _bsifsortid;
        private java.lang.String _bdifsortname;
        private java.lang.Integer _bsifpublishid;
        private java.lang.String _bsifpublishname;
        private java.util.Date _bsifpublishdate;
        private java.lang.String _bsifauthor;
        private java.lang.String _bsifeditor;
        private java.lang.String _bsifholdtrue;
        private java.lang.Integer _bsifimpression;
        private double _bsifword;
        private java.util.Date _bsifappenddate;
        private java.lang.String _bsifappenddept;
        private float _bsifprice;
        private float _bsifmailprice;
        private java.lang.String _bsifintr;
        private java.lang.String _bsifcover;
        private java.lang.String _bsifcatalong;
        private java.lang.String _bsifmemo;
        private java.lang.String _remark1;
        private java.lang.String _remark2;
        private java.lang.String _remark3;
        private java.lang.String _remark4;
        private java.lang.String _remark5;

        // constructors
        public BaseMTeachbeseinfoTab()
        {
                initialize();
        }

        /**
         * Constructor for primary key
         */
        public BaseMTeachbeseinfoTab(long _id)
        {
                this.setId(_id);
                initialize();
        }

        /**
         * Constructor for required fields
         */
        public BaseMTeachbeseinfoTab(long _id, java.lang.String _bsifbookname)
        {
                this.setId(_id);
                this.setBsifbookname(_bsifbookname);
                initialize();
        }

        protected void initialize()
        {
        }

        /**
         * Return the unique identifier of this class
         *
         * @hibernate.id generator-class="sequence"
         * column="BSIFID"
         */
        public long getId()
        {
                return _id;
        }

        /**
         * Set the unique identifier of this class
         *
         * @param _id the new ID
         */
        public void setId(long _id)
        {
                this._id = _id;
                this.hashCode = Integer.MIN_VALUE;
        }

        /**
         * Return the value associated with the column: ISBN
         */
        public java.lang.String getIsbn()
        {
                return _isbn;
        }

        /**
         * Set the value related to the column: ISBN
         *
         * @param _isbn the ISBN value
         */
        public void setIsbn(java.lang.String _isbn)
        {
                this._isbn = _isbn;
        }

        /**
         * Return the value associated with the column: BSIFBOOKNAME
         */
        public java.lang.String getBsifbookname()
        {
                return _bsifbookname;
        }

        /**
         * Set the value related to the column: BSIFBOOKNAME
         *
         * @param _bsifbookname the BSIFBOOKNAME value
         */
        public void setBsifbookname(java.lang.String _bsifbookname)
        {
                this._bsifbookname = _bsifbookname;
        }

        /**
         * Return the value associated with the column: BSIFSORTID
         */
        public java.lang.Integer getBsifsortid()
        {
                return _bsifsortid;
        }

        /**
         * Set the value related to the column: BSIFSORTID
         *
         * @param _bsifsortid the BSIFSORTID value
         */
        public void setBsifsortid(java.lang.Integer _bsifsortid)
        {
                this._bsifsortid = _bsifsortid;
        }

        /**
         * Return the value associated with the column: BDIFSORTNAME
         */
        public java.lang.String getBdifsortname()
        {
                return _bdifsortname;
        }

        /**
         * Set the value related to the column: BDIFSORTNAME
         *
         * @param _bdifsortname the BDIFSORTNAME value
         */
        public void setBdifsortname(java.lang.String _bdifsortname)
        {
                this._bdifsortname = _bdifsortname;
        }

        /**
         * Return the value associated with the column: BSIFPUBLISHID
         */
        public java.lang.Integer getBsifpublishid()
        {
                return _bsifpublishid;
        }

        /**
         * Set the value related to the column: BSIFPUBLISHID
         *
         * @param _bsifpublishid the BSIFPUBLISHID value
         */
        public void setBsifpublishid(java.lang.Integer _bsifpublishid)
        {
                this._bsifpublishid = _bsifpublishid;
        }

        /**
         * Return the value associated with the column: BSIFPUBLISHNAME
         */
        public java.lang.String getBsifpublishname()
        {
                return _bsifpublishname;
        }

        /**
         * Set the value related to the column: BSIFPUBLISHNAME
         *
         * @param _bsifpublishname the BSIFPUBLISHNAME value
         */
        public void setBsifpublishname(java.lang.String _bsifpublishname)
        {
                this._bsifpublishname = _bsifpublishname;
        }

        /**
         * Return the value associated with the column: BSIFPUBLISHDATE
         */
        public java.util.Date getBsifpublishdate()
        {
                return _bsifpublishdate;
        }

        /**
         * Set the value related to the column: BSIFPUBLISHDATE
         *
         * @param _bsifpublishdate the BSIFPUBLISHDATE value
         */
        public void setBsifpublishdate(java.util.Date _bsifpublishdate)
        {
                this._bsifpublishdate = _bsifpublishdate;
        }

        /**
         * Return the value associated with the column: BSIFAUTHOR
         */
        public java.lang.String getBsifauthor()
        {
                return _bsifauthor;
        }

        /**
         * Set the value related to the column: BSIFAUTHOR
         *
         * @param _bsifauthor the BSIFAUTHOR value
         */
        public void setBsifauthor(java.lang.String _bsifauthor)
        {
                this._bsifauthor = _bsifauthor;
        }

        /**
         * Return the value associated with the column: BSIFEDITOR
         */
        public java.lang.String getBsifeditor()
        {
                return _bsifeditor;
        }

        /**
         * Set the value related to the column: BSIFEDITOR
         *
         * @param _bsifeditor the BSIFEDITOR value
         */
        public void setBsifeditor(java.lang.String _bsifeditor)
        {
                this._bsifeditor = _bsifeditor;
        }

        /**
         * Return the value associated with the column: BSIFHOLDTRUE
         */
        public java.lang.String getBsifholdtrue()
        {
                return _bsifholdtrue;
        }

        /**
         * Set the value related to the column: BSIFHOLDTRUE
         *
         * @param _bsifholdtrue the BSIFHOLDTRUE value
         */
        public void setBsifholdtrue(java.lang.String _bsifholdtrue)
        {
                this._bsifholdtrue = _bsifholdtrue;
        }

        /**
         * Return the value associated with the column: BSIFIMPRESSION
         */
        public java.lang.Integer getBsifimpression()
        {
                return _bsifimpression;
        }

        /**
         * Set the value related to the column: BSIFIMPRESSION
         *
         * @param _bsifimpression the BSIFIMPRESSION value
         */
        public void setBsifimpression(java.lang.Integer _bsifimpression)
        {
                this._bsifimpression = _bsifimpression;
        }

        /**
         * Return the value associated with the column: BSIFWORD
         */
        public double getBsifword()
        {
                return _bsifword;
        }

        /**
         * Set the value related to the column: BSIFWORD
         *
         * @param _bsifword the BSIFWORD value
         */
        public void setBsifword(double _bsifword)
        {
                this._bsifword = _bsifword;
        }

        /**
         * Return the value associated with the column: BSIFAPPENDDATE
         */
        public java.util.Date getBsifappenddate()
        {
                return _bsifappenddate;
        }

        /**
         * Set the value related to the column: BSIFAPPENDDATE
         *
         * @param _bsifappenddate the BSIFAPPENDDATE value
         */
        public void setBsifappenddate(java.util.Date _bsifappenddate)
        {
                this._bsifappenddate = _bsifappenddate;
        }

        /**
         * Return the value associated with the column: BSIFAPPENDDEPT
         */
        public java.lang.String getBsifappenddept()
        {
                return _bsifappenddept;
        }

        /**
         * Set the value related to the column: BSIFAPPENDDEPT
         *
         * @param _bsifappenddept the BSIFAPPENDDEPT value
         */
        public void setBsifappenddept(java.lang.String _bsifappenddept)
        {
                this._bsifappenddept = _bsifappenddept;
        }

        /**
         * Return the value associated with the column: BSIFPRICE
         */
        public float getBsifprice()
        {
                return _bsifprice;
        }

        /**
         * Set the value related to the column: BSIFPRICE
         *
         * @param _bsifprice the BSIFPRICE value
         */
        public void setBsifprice(float _bsifprice)
        {
                this._bsifprice = _bsifprice;
        }

        /**
         * Return the value associated with the column: BSIFMAILPRICE
         */
        public float getBsifmailprice()
        {
                return _bsifmailprice;
        }

        /**
         * Set the value related to the column: BSIFMAILPRICE
         *
         * @param _bsifmailprice the BSIFMAILPRICE value
         */
        public void setBsifmailprice(float _bsifmailprice)
        {
                this._bsifmailprice = _bsifmailprice;
        }

        /**
         * Return the value associated with the column: BSIFINTR
         */
        public java.lang.String getBsifintr()
        {
                return _bsifintr;
        }

        /**
         * Set the value related to the column: BSIFINTR
         *
         * @param _bsifintr the BSIFINTR value
         */
        public void setBsifintr(java.lang.String _bsifintr)
        {
                this._bsifintr = _bsifintr;
        }

        /**
         * Return the value associated with the column: BSIFCOVER
         */
        public java.lang.String getBsifcover()
        {
                return _bsifcover;
        }

        /**
         * Set the value related to the column: BSIFCOVER
         *
         * @param _bsifcover the BSIFCOVER value
         */
        public void setBsifcover(java.lang.String _bsifcover)
        {
                this._bsifcover = _bsifcover;
        }

        /**
         * Return the value associated with the column: BSIFCATALONG
         */
        public java.lang.String getBsifcatalong()
        {
                return _bsifcatalong;
        }

        /**
         * Set the value related to the column: BSIFCATALONG
         *
         * @param _bsifcatalong the BSIFCATALONG value
         */
        public void setBsifcatalong(java.lang.String _bsifcatalong)
        {
                this._bsifcatalong = _bsifcatalong;
        }

        /**
         * Return the value associated with the column: BSIFMEMO
         */
        public java.lang.String getBsifmemo()
        {
                return _bsifmemo;
        }

        /**
         * Set the value related to the column: BSIFMEMO
         *
         * @param _bsifmemo the BSIFMEMO value
         */
        public void setBsifmemo(java.lang.String _bsifmemo)
        {
                this._bsifmemo = _bsifmemo;
        }

        /**
         * Return the value associated with the column: REMARK1
         */
        public java.lang.String getRemark1()
        {
                return _remark1;
        }

        /**
         * Set the value related to the column: REMARK1
         *
         * @param _remark1 the REMARK1 value
         */
        public void setRemark1(java.lang.String _remark1)
        {
                this._remark1 = _remark1;
        }

        /**
         * Return the value associated with the column: REMARK2
         */
        public java.lang.String getRemark2()
        {
                return _remark2;
        }

        /**
         * Set the value related to the column: REMARK2
         *
         * @param _remark2 the REMARK2 value
         */
        public void setRemark2(java.lang.String _remark2)
        {
                this._remark2 = _remark2;
        }

        /**
         * Return the value associated with the column: REMARK3
         */
        public java.lang.String getRemark3()
        {
                return _remark3;
        }

        /**
         * Set the value related to the column: REMARK3
         *
         * @param _remark3 the REMARK3 value
         */
        public void setRemark3(java.lang.String _remark3)
        {
                this._remark3 = _remark3;
        }

        /**
         * Return the value associated with the column: REMARK4
         */
        public java.lang.String getRemark4()
        {
                return _remark4;
        }

        /**
         * Set the value related to the column: REMARK4
         *
         * @param _remark4 the REMARK4 value
         */
        public void setRemark4(java.lang.String _remark4)
        {
                this._remark4 = _remark4;
        }

        /**
         * Return the value associated with the column: REMARK5
         */
        public java.lang.String getRemark5()
        {
                return _remark5;
        }

        /**
         * Set the value related to the column: REMARK5
         *
         * @param _remark5 the REMARK5 value
         */
        public void setRemark5(java.lang.String _remark5)
        {
                this._remark5 = _remark5;
        }

        public boolean equals(Object obj)
        {
                if (null == obj)
                {
                        return false;
                }

                if (!(obj instanceof com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachbeseinfoTab))
                {
                        return false;
                }
                else
                {
                        com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachbeseinfoTab mObj =
                                (com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachbeseinfoTab) obj;

                        return (this.getId() == mObj.getId());
                }
        }

        public int hashCode()
        {
                if (Integer.MIN_VALUE == this.hashCode)
                {
                        return (int) this.getId();
                }

                return this.hashCode;
        }

        public String toString()
        {
                return super.toString();
        }
}
