package com.ulearning.ulms.content.schoolbook.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 * <p/>
 * This is an object that contains data related to the M_TEACHSTOR_ITEM_TAB table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class table="M_TEACHSTOR_ITEM_TAB"
 */
public abstract class BaseMTeachstorItemTab implements Serializable
{
        public static String PROP_TCITEMTCLIENTID = "tcitemtclientid";
        public static String PROP_TCITEMSUPPLIERID = "tcitemsupplierid";
        public static String PROP_TCITEMPRICE = "tcitemprice";
        public static String PROP_TCITEMSOURCENAME = "tcitemsourcename";
        public static String PROP_TCITEMTOTAL = "tcitemtotal";
        public static String PROP_TCMAINID = "tcmainid";
        public static String PROP_TCITEMSOURCEID = "tcitemsourceid";
        public static String PROP_BSIFBOOKNAME = "bsifbookname";
        public static String PROP_TCITEMSUPPLIERNAME = "tcitemsuppliername";
        public static String PROP_BSIFID = "bsifid";
        public static String PROP_TCITEMQUANTITY = "tcitemquantity";
        public static String PROP_TCITEMTCLIENTNAME = "tcitemtclientname";
        public static String PROP_ID = "id";
        private int hashCode = Integer.MIN_VALUE;

        // primary key
        private long _id;

        // fields
        private java.lang.Integer _tcmainid;
        private java.lang.Integer _bsifid;
        private java.lang.String _bsifbookname;
        private float _tcitemprice;
        private Integer _tcitemquantity;
        private float _tcitemtotal;
        private java.lang.Integer _tcitemtclientid;
        private java.lang.String _tcitemtclientname;
        private java.lang.Integer _tcitemsupplierid;
        private java.lang.String _tcitemsuppliername;
        private java.lang.Integer _tcitemsourceid;
        private java.lang.String _tcitemsourcename;

        // constructors
        public BaseMTeachstorItemTab()
        {
                initialize();
        }

        /**
         * Constructor for primary key
         */
        public BaseMTeachstorItemTab(long _id)
        {
                this.setId(_id);
                initialize();
        }

        protected void initialize()
        {
        }

        /**
         * Return the unique identifier of this class
         *
         * @hibernate.id generator-class="sequence"
         * column="TCITEMID"
         */
        public long getId()
        {
                return _id;
        }

        /**
         * Set the unique identifier of this class
         *
         * @param _id the new ID
         */
        public void setId(long _id)
        {
                this._id = _id;
                this.hashCode = Integer.MIN_VALUE;
        }

        /**
         * Return the value associated with the column: TCMAINID
         */
        public java.lang.Integer getTcmainid()
        {
                return _tcmainid;
        }

        /**
         * Set the value related to the column: TCMAINID
         *
         * @param _tcmainid the TCMAINID value
         */
        public void setTcmainid(java.lang.Integer _tcmainid)
        {
                this._tcmainid = _tcmainid;
        }

        /**
         * Return the value associated with the column: BSIFID
         */
        public java.lang.Integer getBsifid()
        {
                return _bsifid;
        }

        /**
         * Set the value related to the column: BSIFID
         *
         * @param _bsifid the BSIFID value
         */
        public void setBsifid(java.lang.Integer _bsifid)
        {
                this._bsifid = _bsifid;
        }

        /**
         * Return the value associated with the column: BSIFBOOKNAME
         */
        public java.lang.String getBsifbookname()
        {
                return _bsifbookname;
        }

        /**
         * Set the value related to the column: BSIFBOOKNAME
         *
         * @param _bsifbookname the BSIFBOOKNAME value
         */
        public void setBsifbookname(java.lang.String _bsifbookname)
        {
                this._bsifbookname = _bsifbookname;
        }

        /**
         * Return the value associated with the column: TCITEMPRICE
         */
        public float getTcitemprice()
        {
                return _tcitemprice;
        }

        /**
         * Set the value related to the column: TCITEMPRICE
         *
         * @param _tcitemprice the TCITEMPRICE value
         */
        public void setTcitemprice(float _tcitemprice)
        {
                this._tcitemprice = _tcitemprice;
        }

        /**
         * Return the value associated with the column: TCITEMQUANTITY
         */
        public Integer getTcitemquantity()
        {
                return _tcitemquantity;
        }

        /**
         * Set the value related to the column: TCITEMQUANTITY
         *
         * @param _tcitemquantity the TCITEMQUANTITY value
         */
        public void setTcitemquantity(Integer _tcitemquantity)
        {
                this._tcitemquantity = _tcitemquantity;
        }

        /**
         * Return the value associated with the column: TCITEMTOTAL
         */
        public float getTcitemtotal()
        {
                return _tcitemtotal;
        }

        /**
         * Set the value related to the column: TCITEMTOTAL
         *
         * @param _tcitemtotal the TCITEMTOTAL value
         */
        public void setTcitemtotal(float _tcitemtotal)
        {
                this._tcitemtotal = _tcitemtotal;
        }

        /**
         * Return the value associated with the column: TCITEMTCLIENTID
         */
        public java.lang.Integer getTcitemtclientid()
        {
                return _tcitemtclientid;
        }

        /**
         * Set the value related to the column: TCITEMTCLIENTID
         *
         * @param _tcitemtclientid the TCITEMTCLIENTID value
         */
        public void setTcitemtclientid(java.lang.Integer _tcitemtclientid)
        {
                this._tcitemtclientid = _tcitemtclientid;
        }

        /**
         * Return the value associated with the column: TCITEMTCLIENTNAME
         */
        public java.lang.String getTcitemtclientname()
        {
                return _tcitemtclientname;
        }

        /**
         * Set the value related to the column: TCITEMTCLIENTNAME
         *
         * @param _tcitemtclientname the TCITEMTCLIENTNAME value
         */
        public void setTcitemtclientname(java.lang.String _tcitemtclientname)
        {
                this._tcitemtclientname = _tcitemtclientname;
        }

        /**
         * Return the value associated with the column: TCITEMSUPPLIERID
         */
        public java.lang.Integer getTcitemsupplierid()
        {
                return _tcitemsupplierid;
        }

        /**
         * Set the value related to the column: TCITEMSUPPLIERID
         *
         * @param _tcitemsupplierid the TCITEMSUPPLIERID value
         */
        public void setTcitemsupplierid(java.lang.Integer _tcitemsupplierid)
        {
                this._tcitemsupplierid = _tcitemsupplierid;
        }

        /**
         * Return the value associated with the column: TCITEMSUPPLIERNAME
         */
        public java.lang.String getTcitemsuppliername()
        {
                return _tcitemsuppliername;
        }

        /**
         * Set the value related to the column: TCITEMSUPPLIERNAME
         *
         * @param _tcitemsuppliername the TCITEMSUPPLIERNAME value
         */
        public void setTcitemsuppliername(java.lang.String _tcitemsuppliername)
        {
                this._tcitemsuppliername = _tcitemsuppliername;
        }

        /**
         * Return the value associated with the column: TCITEMSOURCEID
         */
        public java.lang.Integer getTcitemsourceid()
        {
                return _tcitemsourceid;
        }

        /**
         * Set the value related to the column: TCITEMSOURCEID
         *
         * @param _tcitemsourceid the TCITEMSOURCEID value
         */
        public void setTcitemsourceid(java.lang.Integer _tcitemsourceid)
        {
                this._tcitemsourceid = _tcitemsourceid;
        }

        /**
         * Return the value associated with the column: TCITEMSOURCENAME
         */
        public java.lang.String getTcitemsourcename()
        {
                return _tcitemsourcename;
        }

        /**
         * Set the value related to the column: TCITEMSOURCENAME
         *
         * @param _tcitemsourcename the TCITEMSOURCENAME value
         */
        public void setTcitemsourcename(java.lang.String _tcitemsourcename)
        {
                this._tcitemsourcename = _tcitemsourcename;
        }

        public boolean equals(Object obj)
        {
                if (null == obj)
                {
                        return false;
                }

                if (!(obj instanceof com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachstorItemTab))
                {
                        return false;
                }
                else
                {
                        com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachstorItemTab mObj =
                                (com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachstorItemTab) obj;

                        return (this.getId() == mObj.getId());
                }
        }

        public int hashCode()
        {
                if (Integer.MIN_VALUE == this.hashCode)
                {
                        return (int) this.getId();
                }

                return this.hashCode;
        }

        public String toString()
        {
                return super.toString();
        }
}
