package com.ulearning.ulms.content.schoolbook.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 * <p/>
 * This is an object that contains data related to the M_TEACHMAILBILL_TAB table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class table="M_TEACHMAILBILL_TAB"
 */
public abstract class BaseMTeachmailbillTab implements Serializable
{
        public static String PROP_TCMLOPERATOR = "tcmloperator";
        public static String PROP_TCMLTOTAL = "tcmltotal";
        public static String PROP_TCMLMAILPRICE = "tcmlmailprice";
        public static String PROP_TCMLQUANTITY = "tcmlquantity";
        public static String PROP_TCMLPHONE = "tcmlphone";
        public static String PROP_REMARK3 = "remark3";
        public static String PROP_REMARK1 = "remark1";
        public static String PROP_BSIFBOOKNAME = "bsifbookname";
        public static String PROP_TCMLDEPT = "tcmldept";
        public static String PROP_REMARK4 = "remark4";
        public static String PROP_REMARK2 = "remark2";
        public static String PROP_BSIFID = "bsifid";
        public static String PROP_REMARK5 = "remark5";
        public static String PROP_ID = "id";
        public static String PROP_TCMLMAN = "tcmlman";
        private int hashCode = Integer.MIN_VALUE;

        // primary key
        private long _id;

        // fields
        private java.lang.Integer _bsifid;
        private java.lang.String _bsifbookname;
        private java.lang.String _tcmldept;
        private java.lang.String _tcmlman;
        private float _tcmlmailprice;
        private java.lang.Integer _tcmlquantity;
        private float _tcmltotal;
        private java.lang.String _tcmlphone;
        private java.lang.String _tcmloperator;
        private java.lang.String _remark1;
        private java.lang.String _remark2;
        private java.lang.String _remark3;
        private java.lang.String _remark4;
        private java.lang.String _remark5;

        // constructors
        public BaseMTeachmailbillTab()
        {
                initialize();
        }

        /**
         * Constructor for primary key
         */
        public BaseMTeachmailbillTab(long _id)
        {
                this.setId(_id);
                initialize();
        }

        protected void initialize()
        {
        }

        /**
         * Return the unique identifier of this class
         *
         * @hibernate.id generator-class="sequence"
         * column="TCMLID"
         */
        public long getId()
        {
                return _id;
        }

        /**
         * Set the unique identifier of this class
         *
         * @param _id the new ID
         */
        public void setId(long _id)
        {
                this._id = _id;
                this.hashCode = Integer.MIN_VALUE;
        }

        /**
         * Return the value associated with the column: BSIFID
         */
        public java.lang.Integer getBsifid()
        {
                return _bsifid;
        }

        /**
         * Set the value related to the column: BSIFID
         *
         * @param _bsifid the BSIFID value
         */
        public void setBsifid(java.lang.Integer _bsifid)
        {
                this._bsifid = _bsifid;
        }

        /**
         * Return the value associated with the column: BSIFBOOKNAME
         */
        public java.lang.String getBsifbookname()
        {
                return _bsifbookname;
        }

        /**
         * Set the value related to the column: BSIFBOOKNAME
         *
         * @param _bsifbookname the BSIFBOOKNAME value
         */
        public void setBsifbookname(java.lang.String _bsifbookname)
        {
                this._bsifbookname = _bsifbookname;
        }

        /**
         * Return the value associated with the column: TCMLDEPT
         */
        public java.lang.String getTcmldept()
        {
                return _tcmldept;
        }

        /**
         * Set the value related to the column: TCMLDEPT
         *
         * @param _tcmldept the TCMLDEPT value
         */
        public void setTcmldept(java.lang.String _tcmldept)
        {
                this._tcmldept = _tcmldept;
        }

        /**
         * Return the value associated with the column: TCMLMAN
         */
        public java.lang.String getTcmlman()
        {
                return _tcmlman;
        }

        /**
         * Set the value related to the column: TCMLMAN
         *
         * @param _tcmlman the TCMLMAN value
         */
        public void setTcmlman(java.lang.String _tcmlman)
        {
                this._tcmlman = _tcmlman;
        }

        /**
         * Return the value associated with the column: TCMLMAILPRICE
         */
        public float getTcmlmailprice()
        {
                return _tcmlmailprice;
        }

        /**
         * Set the value related to the column: TCMLMAILPRICE
         *
         * @param _tcmlmailprice the TCMLMAILPRICE value
         */
        public void setTcmlmailprice(float _tcmlmailprice)
        {
                this._tcmlmailprice = _tcmlmailprice;
        }

        /**
         * Return the value associated with the column: TCMLQUANTITY
         */
        public java.lang.Integer getTcmlquantity()
        {
                return _tcmlquantity;
        }

        /**
         * Set the value related to the column: TCMLQUANTITY
         *
         * @param _tcmlquantity the TCMLQUANTITY value
         */
        public void setTcmlquantity(java.lang.Integer _tcmlquantity)
        {
                this._tcmlquantity = _tcmlquantity;
        }

        /**
         * Return the value associated with the column: TCMLTOTAL
         */
        public float getTcmltotal()
        {
                return _tcmltotal;
        }

        /**
         * Set the value related to the column: TCMLTOTAL
         *
         * @param _tcmltotal the TCMLTOTAL value
         */
        public void setTcmltotal(float _tcmltotal)
        {
                this._tcmltotal = _tcmltotal;
        }

        /**
         * Return the value associated with the column: TCMLPHONE
         */
        public java.lang.String getTcmlphone()
        {
                return _tcmlphone;
        }

        /**
         * Set the value related to the column: TCMLPHONE
         *
         * @param _tcmlphone the TCMLPHONE value
         */
        public void setTcmlphone(java.lang.String _tcmlphone)
        {
                this._tcmlphone = _tcmlphone;
        }

        /**
         * Return the value associated with the column: TCMLOPERATOR
         */
        public java.lang.String getTcmloperator()
        {
                return _tcmloperator;
        }

        /**
         * Set the value related to the column: TCMLOPERATOR
         *
         * @param _tcmloperator the TCMLOPERATOR value
         */
        public void setTcmloperator(java.lang.String _tcmloperator)
        {
                this._tcmloperator = _tcmloperator;
        }

        /**
         * Return the value associated with the column: REMARK1
         */
        public java.lang.String getRemark1()
        {
                return _remark1;
        }

        /**
         * Set the value related to the column: REMARK1
         *
         * @param _remark1 the REMARK1 value
         */
        public void setRemark1(java.lang.String _remark1)
        {
                this._remark1 = _remark1;
        }

        /**
         * Return the value associated with the column: REMARK2
         */
        public java.lang.String getRemark2()
        {
                return _remark2;
        }

        /**
         * Set the value related to the column: REMARK2
         *
         * @param _remark2 the REMARK2 value
         */
        public void setRemark2(java.lang.String _remark2)
        {
                this._remark2 = _remark2;
        }

        /**
         * Return the value associated with the column: REMARK3
         */
        public java.lang.String getRemark3()
        {
                return _remark3;
        }

        /**
         * Set the value related to the column: REMARK3
         *
         * @param _remark3 the REMARK3 value
         */
        public void setRemark3(java.lang.String _remark3)
        {
                this._remark3 = _remark3;
        }

        /**
         * Return the value associated with the column: REMARK4
         */
        public java.lang.String getRemark4()
        {
                return _remark4;
        }

        /**
         * Set the value related to the column: REMARK4
         *
         * @param _remark4 the REMARK4 value
         */
        public void setRemark4(java.lang.String _remark4)
        {
                this._remark4 = _remark4;
        }

        /**
         * Return the value associated with the column: REMARK5
         */
        public java.lang.String getRemark5()
        {
                return _remark5;
        }

        /**
         * Set the value related to the column: REMARK5
         *
         * @param _remark5 the REMARK5 value
         */
        public void setRemark5(java.lang.String _remark5)
        {
                this._remark5 = _remark5;
        }

        public boolean equals(Object obj)
        {
                if (null == obj)
                {
                        return false;
                }

                if (!(obj instanceof com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachmailbillTab))
                {
                        return false;
                }
                else
                {
                        com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachmailbillTab mObj =
                                (com.ulearning.ulms.content.schoolbook.model.base.BaseMTeachmailbillTab) obj;

                        return (this.getId() == mObj.getId());
                }
        }

        public int hashCode()
        {
                if (Integer.MIN_VALUE == this.hashCode)
                {
                        return (int) this.getId();
                }

                return this.hashCode;
        }

        public String toString()
        {
                return super.toString();
        }
}
